### ISSUE TITLE
Skrivefeil i readme :(

### ISSUE THREAD

**Issue by MBMarsell** [JoaPerss/AUDtoNOK#1]
This simple currency converter is a reslt of my laziness to type "X australian dollars to norwegian kroner" into Google everytime I wanted to convert prices when i lived in Australia. => This simple currency converter is a result of my laziness to type "X australian dollars to norwegian kroner" into Google everytime I wanted to convert prices when i lived in Australia.

**Comment by JoaPerss** [comment]
Thank you for the proposed solution!
